export const actionTypes = {
  //book actions
  FETCH_BOOKS: "FETCH_BOOKS",
  REMOVE_BOOK_CART: "REMOVE_BOOK_FROM_CART",
  ADD_BOOK_CART: "ADD_BOOK_TO_CART",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
};
